USE [master]
GO

/****** Object:  Database [FAQMan]    Script Date: 3/18/2013 12:22:40 PM ******/
CREATE DATABASE [FAQMan] ON  PRIMARY 
( NAME = N'FAQMan', FILENAME = N'c:\MSSQL\Data\FAQMan.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'FAQMan_log', FILENAME = N'c:\MSSQL\Data\FAQMan_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [FAQMan] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FAQMan].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FAQMan] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FAQMan] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FAQMan] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FAQMan] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FAQMan] SET ARITHABORT OFF 
GO

ALTER DATABASE [FAQMan] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FAQMan] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [FAQMan] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FAQMan] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FAQMan] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FAQMan] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FAQMan] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FAQMan] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FAQMan] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FAQMan] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FAQMan] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FAQMan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FAQMan] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FAQMan] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FAQMan] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FAQMan] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FAQMan] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FAQMan] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FAQMan] SET RECOVERY FULL 
GO

ALTER DATABASE [FAQMan] SET  MULTI_USER 
GO

ALTER DATABASE [FAQMan] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FAQMan] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FAQMan] SET  READ_WRITE 
GO


